### ISSUE TITLE
Add the magic-nix-cache binaries to the GitHub release

### ISSUE THREAD

**Issue by terlar** [DeterminateSystems/magic-nix-cache-action#7]
Would it be possible to add the `magic-nix-cache` binaries to the GitHub release?

I have an environment where Internet access is limited and would like to utilize `source-url` or `source-binary`. I do have access to GitHub in this restricted environment.

**Comment by grahamc** [comment]
Will this solve it for you, @terlar? We're pushing v0.1.1 shortly.

**Comment by terlar** [comment]
Hmm, I don't see a difference. The release includes the source code, but not the binaries for magic-nix-cache:
https://github.com/DeterminateSystems/magic-nix-cache-action/releases

I'm thinking similar to what you do for nix-installer:
https://github.com/DeterminateSystems/nix-installer/releases

**Comment by cole-h** [comment]
Yes, that's because the release hasn't actually been pushed out yet because of GHA weirdness. I'm still working on getting that release out, and that one (0.1.1) will have binaries on the GitHub release page, just like our `nix-installer`.

**Comment by terlar** [comment]
Ah, okay, sorry then I understand. Thank you, looking forward to that.

**Comment by terlar** [comment]
I see now that I linked the wrong page, but yes, thank you now it works! Used the release together with `source-url`.
